export const SECONDS_PER_MINUTE = 60;
export const DEFAULT_WORK_DURATION = 25;
export const DEFAULT_SHORT_BREAK_DURATION = 5;
export const DEFAULT_LONG_BREAK_DURATION = 15;
export const DEFAULT_SHORT_BREAKS_BEFORE_LONG = 4;